services:
  postgres:
    container_name: szynex
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

    ports:
      - "5001:5432"
    networks:
      - postgres
    restart: unless-stopped



networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: